# Welcome to Jekyll!
# This config file is meant for settings that affect your entire site.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the server process.

# Basic Site Settings
locale: "en-US"
title: "Raghuwansh's Homepage"
logo: /assets/img/headshot_raghu.png
title_separator: "Welcome to my profile! I am a 27-year-old Machine Learning Engineer currently working at Stellantis, based in the beautiful city of Paris. Born and raised in India, I have always been deeply passionate about mathematics, technology, and machine learning, which have shaped my academic and professional journey. I hold a Bachelor's degree in Engineering with a minor in Mathematics from IIT BHU Varanasi. To further nurture my passion for data and innovation, I pursued a double master's degree in Machine Learning and Business Analytics from CentraleSupélec and ESSEC Business School. With a strong foundation in analytics and a drive to push the boundaries of AI, I am committed to developing my career in this exciting field. I am eager to contribute to innovative solutions and explore cutting-edge advancements that blend technology with real-world impact."
name: "Raghuwansh Raj Mishra"
description: "Machine Learning Engineer | Data Scientist | AI Enthusiast"
url: "https://rajraghuwansh.github.io"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. "/blog"
repository: "rajraghuwansh/rajraghuwansh.github.io"

# Site Author - Controls what appears in the author profile sidebar.
author:
  # Biographic information
  avatar: "assets/img/headshot_raghu.png"
  name: "Raghuwansh Raj Mishra"
  bio: "Machine Learning Engineer at Stellantis | Passionate about AI, Data Science, and Innovation"
  location: "Paris, France"
  employer: "Stellantis"
  uri:  # URL (optional)
  email: "raghuwansh.rajm@gmail.com"

  # Academic websites
  arxiv:  # URL (optional)

  # Repositories and software development
  github: "rajraghuwansh"

  # Social media
  bluesky:  # Bluesky username (optional)
  facebook:  # Facebook username (optional)

# Site Settings
teaser:  # filename of teaser fallback image placed in /images/, e.g. "500x300.png"
breadcrumbs: false  # true, false (default)
words_per_minute: 160
future: true
read_more: "disabled"  # if enabled, adds "Read more" links to excerpts
talkmap_link: false  # change to true to add link to talkmap on talks page
comments:
  provider:  # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname:
  discourse:
    server:  # e.g., meta.discourse.org
  facebook:
    appid:
    num_posts:  # 5 (default)
    colorscheme:  # "light" (default), "dark"
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"  # "master", "gh-pages"
  commitMessage: "New comment."
  filename: "comment-{@timestamp}"
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"  # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide: false  # change to true to hide the RSS feed in the footer
  path:  # blank (default) uses feed.xml

# Default settings for pages and collections
defaults:
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
