title: Raghuwansh Raj
logo: /assets/img/headshot_raghu.png
location: Paris, France
github: "rajraghuwansh"
Linkedin: "https://www.linkedin.com/in/raghuwansh/"
show_downloads: false
theme: jekyll-theme-minimal
